name: Publish to NPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Build Variables
        run: |
          echo "NEXT_VERSION=3.0.0-alpha.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Set package.json version
        uses: HarmvZ/set-package-json-version-action@v0.2.5
        with:
          version: ${{ env.NEXT_VERSION }}

      - name: Install NPM Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Publish to NPM
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
